<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\shared\Throughline.Common.Presentation\Throughline.Common.Presentation\Throughline.Common.Presentation.csproj"/>
        <ProjectReference Include="..\Throughline.Modules.Ordering.Application\Throughline.Modules.Ordering.Application.csproj"/>
        <ProjectReference Include="..\Throughline.Modules.Ordering.Domain\Throughline.Modules.Ordering.Domain.csproj"/>
        <ProjectReference Include="..\Throughline.Modules.Ordering.Infrastructure\Throughline.Modules.Ordering.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
</Project>
