// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Throughline.Modules.Receiving.Infrastructure.Db;

#nullable disable

namespace Throughline.Modules.Receiving.Infrastructure.Migrations
{
    [DbContext(typeof(ReceivingDbContext))]
    partial class ReceivingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("receiving")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Throughline.Modules.Receiving.Application.ReceiveDelivery.Models.DeliverySubmission", b =>
                {
                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.HasKey("OwnerId", "DeliveryId")
                        .HasName("pk_delivery_submissions");

                    b.ToTable("delivery_submissions", "receiving");
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Domain.DeliveryReceipts.DeliveryReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_receipt_id");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("receipt_number");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_on");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Shipment", "Throughline.Modules.Receiving.Domain.DeliveryReceipts.DeliveryReceipt.Shipment#Shipment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BillOfLading")
                                .HasColumnType("text")
                                .HasColumnName("bill_of_lading");

                            b1.Property<string>("ContainerNumber")
                                .HasColumnType("text")
                                .HasColumnName("container_number");

                            b1.Property<string>("ShipperName")
                                .HasColumnType("text")
                                .HasColumnName("shipper_name");

                            b1.Property<string>("ShipperReference")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipper_reference");

                            b1.Property<string>("TrailerNumber")
                                .HasColumnType("text")
                                .HasColumnName("trailer_number");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CarrierScac", "Throughline.Modules.Receiving.Domain.DeliveryReceipts.DeliveryReceipt.Shipment#Shipment.CarrierScac#CarrierScac", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("CarrierId")
                                        .HasColumnType("integer")
                                        .HasColumnName("carrier_id");

                                    b2.Property<string>("CarrierName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("carrier_name");

                                    b2.Property<string>("ScacCode")
                                        .IsRequired()
                                        .HasMaxLength(4)
                                        .HasColumnType("character varying(4)")
                                        .HasColumnName("carrier_scac");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_delivery_receipts");

                    b.HasIndex("OwnerId", "ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_receipts_owner_id_receipt_number");

                    b.ToTable("delivery_receipts", "receiving", t =>
                        {
                            t.HasCheckConstraint("ck_delivery_receipts_trailer_or_container", "trailer_number IS NOT NULL OR container_number IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Domain.Inventory.HoldReason", b =>
                {
                    b.Property<int>("owner_id")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("owner_id", "ReasonCode")
                        .HasName("pk_hold_reasons");

                    b.ToTable("hold_reasons", "receiving");
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Domain.Inventory.InvalidPallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("invalid_pallet_id");

                    b.PrimitiveCollection<string[]>("Exceptions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("exceptions");

                    b.Property<DateTimeOffset?>("ExpiresOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on");

                    b.Property<string>("LicensePlateNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate_number");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RequestLocationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_location_id");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku_code");

                    b.Property<Guid>("delivery_receipt_id")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_receipt_id");

                    b.Property<string>("location_id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_id");

                    b.HasKey("Id")
                        .HasName("pk_invalid_pallets");

                    b.HasIndex("delivery_receipt_id")
                        .HasDatabaseName("ix_invalid_pallets_delivery_receipt_id");

                    b.HasIndex("location_id")
                        .HasDatabaseName("ix_invalid_pallets_location_id");

                    b.ToTable("invalid_pallets", "receiving", t =>
                        {
                            t.HasCheckConstraint("ck_invalid_pallets_exceptions", "cardinality(exceptions) > 0");

                            t.HasCheckConstraint("ck_invalid_pallets_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Domain.Inventory.Pallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("received_pallet_id");

                    b.Property<DateTimeOffset?>("ExpiresOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on");

                    b.Property<string>("LicensePlateNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate_number");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("delivery_receipt_id")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_receipt_id");

                    b.Property<string>("hold_reason_code")
                        .HasColumnType("text")
                        .HasColumnName("hold_reason_code");

                    b.Property<int?>("hold_reason_owner_id")
                        .HasColumnType("integer")
                        .HasColumnName("hold_reason_owner_id");

                    b.Property<string>("location_id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OwnerSku", "Throughline.Modules.Receiving.Domain.Inventory.Pallet.OwnerSku#OwnerSku", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("sku_id");

                            b1.Property<bool>("IsExpirationTracked")
                                .HasColumnType("boolean")
                                .HasColumnName("sku_is_expiration_tracked");

                            b1.Property<bool>("IsLotTracked")
                                .HasColumnType("boolean")
                                .HasColumnName("sku_is_lot_tracked");

                            b1.Property<int>("OwnerId")
                                .HasColumnType("integer")
                                .HasColumnName("owner_id");

                            b1.Property<string>("SkuCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("sku_code");
                        });

                    b.HasKey("Id")
                        .HasName("pk_received_pallets");

                    b.HasIndex("delivery_receipt_id")
                        .HasDatabaseName("ix_received_pallets_delivery_receipt_id");

                    b.HasIndex("location_id")
                        .HasDatabaseName("ix_received_pallets_location_id");

                    b.HasIndex("hold_reason_owner_id", "hold_reason_code")
                        .HasDatabaseName("ix_received_pallets_hold_reason_owner_id_hold_reason_code");

                    b.ToTable("received_pallets", "receiving", t =>
                        {
                            t.HasCheckConstraint("ck_received_pallets_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Domain.Locations.ReceivingLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_type");

                    b.HasKey("Id")
                        .HasName("pk_receiving_locations");

                    b.ToTable("receiving_locations", "receiving");
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Infrastructure.Db.Models.CarrierRecord", b =>
                {
                    b.Property<int>("CarrierId")
                        .HasColumnType("integer")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("carrier_name");

                    b.Property<string>("ScacCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("scac_code");

                    b.HasKey("CarrierId")
                        .HasName("pk_carriers");

                    b.HasIndex("ScacCode")
                        .IsUnique()
                        .HasDatabaseName("ix_carriers_scac_code");

                    b.ToTable("carriers", "receiving");
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Infrastructure.Db.Models.SkuRecord", b =>
                {
                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<bool>("IsExpirationTracked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expiration_tracked");

                    b.Property<bool>("IsLotTracked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lot_tracked");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku_code");

                    b.HasKey("SkuId")
                        .HasName("pk_skus");

                    b.HasIndex("OwnerId", "SkuCode")
                        .IsUnique()
                        .HasDatabaseName("ix_skus_owner_id_sku_code");

                    b.ToTable("skus", "receiving");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Domain.Inventory.InvalidPallet", b =>
                {
                    b.HasOne("Throughline.Modules.Receiving.Domain.DeliveryReceipts.DeliveryReceipt", null)
                        .WithMany("InvalidPallets")
                        .HasForeignKey("delivery_receipt_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invalid_pallets_delivery_receipts_delivery_receipt_id");

                    b.HasOne("Throughline.Modules.Receiving.Domain.Locations.ReceivingLocation", "Location")
                        .WithMany()
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invalid_pallets_receiving_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Domain.Inventory.Pallet", b =>
                {
                    b.HasOne("Throughline.Modules.Receiving.Domain.DeliveryReceipts.DeliveryReceipt", null)
                        .WithMany("Pallets")
                        .HasForeignKey("delivery_receipt_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_received_pallets_delivery_receipts_delivery_receipt_id");

                    b.HasOne("Throughline.Modules.Receiving.Domain.Locations.ReceivingLocation", "Location")
                        .WithMany()
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_received_pallets_receiving_locations_location_id");

                    b.HasOne("Throughline.Modules.Receiving.Domain.Inventory.HoldReason", "HoldReason")
                        .WithMany()
                        .HasForeignKey("hold_reason_owner_id", "hold_reason_code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_received_pallets_hold_reasons_hold_reason");

                    b.Navigation("HoldReason");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Throughline.Modules.Receiving.Domain.DeliveryReceipts.DeliveryReceipt", b =>
                {
                    b.Navigation("InvalidPallets");

                    b.Navigation("Pallets");
                });
#pragma warning restore 612, 618
        }
    }
}
