<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\shared\Throughline.Common.Presentation\Throughline.Common.Presentation\Throughline.Common.Presentation.csproj"/>
        <ProjectReference Include="..\Throughline.Modules.Billing.Application\Throughline.Modules.Billing.Application.csproj"/>
        <ProjectReference Include="..\Throughline.Modules.Billing.Domain\Throughline.Modules.Billing.Domain.csproj"/>
        <ProjectReference Include="..\Throughline.Modules.Billing.Infrastructure\Throughline.Modules.Billing.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
</Project>
