<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\modules\ordering\Throughline.Modules.Ordering\Throughline.Modules.Ordering.csproj"/>
    </ItemGroup>

</Project>
